version: '3.7'
services:
  istart:
    container_name: iSTART
    build:
      context: .
      target: base
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html  
  composer:
    restart: 'no'
    container_name: helix_composer
    image: composer:latest
    command: install --ignore-platform-reqs
    volumes:
      - .:/app/
