version: '3.5'
services:
  redis:
    container_name: istart_redis
    image: "redis:3.2"
    command: "redis-server --appendonly yes"
    ports:
      - 6379:6379
    volumes:
      - .:/data/
  composer:
    restart: 'no'
    container_name: istart_composer
    image: composer:latest
    command: install --ignore-platform-reqs
    volumes:
      - .:/app/
    depends_on:
      - redis
  db:
    container_name: istart-mysql
    image: mysql:8.0.15
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: istart_mysql
      MYSQL_DATABASE: istart_mysql
      MYSQL_USER: istart_mysql
      MYSQL_PASSWORD: istart_mysql
  istart:
    container_name: istart
    build:
      context: .
      target: base
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
      - composer
volumes:
  db_data:
