version: '3'

services:
  webserver:
    container_name: iSTART
    image: csunmetalab/environment:nomi
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/
  composer:
   restart: 'no'
   container_name: iSTART_composer
   image: composer:latest
   command: install
   volumes:
     - .:/app/
